# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: emailservice123

# "service" is the name of this project. 
service: email-service

provider:
  name: aws
  runtime: nodejs20.x

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: /send
          method: post


plugins:
  - serverless-offline
